#!/usr/bin/env python3
"""
COMPASS Pipeline - Interactive Accession List Generator

This tool generates custom Python scripts to fetch SRA accessions from NCBI
based on your specific sampling requirements.

Usage: python3 generate_accession_list.py
"""

import sys
import os
from datetime import datetime

def get_input(prompt, default=None, choices=None):
    """Get user input with optional default and validation"""
    if default:
        prompt = f"{prompt} [{default}]"
    prompt += ": "

    while True:
        response = input(prompt).strip()
        if not response and default:
            return default
        if not response:
            print("Please enter a value")
            continue
        if choices and response not in choices:
            print(f"Please choose from: {', '.join(choices)}")
            continue
        return response

def get_int(prompt, default=None, min_val=None, max_val=None):
    """Get integer input with validation"""
    while True:
        response = get_input(prompt, str(default) if default else None)
        try:
            value = int(response)
            if min_val is not None and value < min_val:
                print(f"Value must be at least {min_val}")
                continue
            if max_val is not None and value > max_val:
                print(f"Value must be at most {max_val}")
                continue
            return value
        except ValueError:
            print("Please enter a valid number")

def generate_script(config):
    """Generate the Python script based on configuration"""

    organism = config['organism']
    start_year = config['start_year']
    end_year = config['end_year']
    strategy = config['strategy']
    samples_per_period = config['samples_per_period']
    platform = config['platform']
    library_source = config['library_source']
    geo_filter = config.get('geo_filter', '')

    # Build organism name for filename
    org_filename = organism.lower().replace(' ', '_')

    # Build search term
    search_parts = [f'{organism}[Organism]']
    if platform != 'Any':
        search_parts.append(f'{platform}[Platform]')
    if library_source != 'Any':
        search_parts.append(f'{library_source}[Source]')
    if geo_filter:
        search_parts.append(f'{geo_filter}[Geographic Location]')

    search_term = ' AND '.join(search_parts)

    script_content = f'''#!/usr/bin/env python3
"""
Fetch {organism} SRA accessions from NCBI
Generated by COMPASS Accession List Generator
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Configuration:
- Organism: {organism}
- Period: {start_year} - {end_year}
- Strategy: {strategy}
- Samples per period: {samples_per_period}
- Platform: {platform}
- Library source: {library_source}
'''

    if geo_filter:
        script_content += f'- Geographic filter: {geo_filter}\n'

    script_content += '''"""
import requests
import random
import time
import xml.etree.ElementTree as ET

def fetch_sra_accessions(year, month, max_results=1000):
    """Fetch SRA accessions from NCBI for a specific month"""
    base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"

    # Format: YYYY/MM
    date_str = f"{year}/{month:02d}"

    params = {
        'db': 'sra',
        'term': f'''

    script_content += f"'{search_term} AND {{date_str}}[Release Date]',\n"

    script_content += '''        'retmax': max_results,
        'retmode': 'json'
    }

    print(f"Fetching {year}-{month:02d}...", end=" ", flush=True)

    try:
        response = requests.get(base_url, params=params, timeout=30)
        data = response.json()

        id_list = data.get('esearchresult', {}).get('idlist', [])
        count = int(data.get('esearchresult', {}).get('count', 0))
        print(f"Found {count} total", end=" ", flush=True)

        # Fetch SRR accessions from UIDs using XML format (more reliable)
        if id_list:
            fetch_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"

            accessions = []
            # Process in batches of 100
            for i in range(0, min(len(id_list), 500), 100):
                batch_ids = id_list[i:i+100]

                fetch_params = {
                    'db': 'sra',
                    'id': ','.join(batch_ids),
                    'rettype': 'full',
                    'retmode': 'xml'
                }

                time.sleep(0.4)  # Be nice to NCBI
                response = requests.get(fetch_url, params=fetch_params, timeout=60)

                # Parse XML to get Run accessions
                try:
                    root = ET.fromstring(response.content)
                    for run in root.findall('.//RUN'):
                        acc = run.get('accession')
                        if acc and acc.startswith('SRR'):
                            accessions.append(acc)
                except ET.ParseError:
                    pass

            print(f"→ Got {len(accessions)} accessions")
            return accessions

    except Exception as e:
        print(f"ERROR: {e}")

    return []

def main():
    print("="*70)
    print(f"Fetching {organism} SRA Accessions from NCBI")
    print(f"Period: {start_year} - {end_year}")
    print(f"Target: {samples_per_period} samples per {strategy.lower()}")
    print("="*70)
    print()

    all_accessions = []
    period_counts = []

    for year in range({start_year}, {end_year + 1}):
        for month in range(1, 13):
            if year == {end_year} and month > 12:  # Adjust end month if needed
                break

            accessions = fetch_sra_accessions(year, month)

            # Sample N random (or all if less than N)
            sample_size = min({samples_per_period}, len(accessions))
            if sample_size > 0:
                sampled = random.sample(accessions, sample_size)
                all_accessions.extend(sampled)
                period_counts.append((year, month, sample_size))
                print(f"  ✓ Sampled {{sample_size}} accessions")
            else:
                print(f"  ✗ No accessions found")

            time.sleep(1)  # Rate limiting for NCBI API

    # Save to file
    output_file = "sra_accessions_{org_filename}_{strategy.lower()}_{samples_per_period}_{start_year}-{end_year}.txt"
    with open(output_file, 'w') as f:
        for acc in all_accessions:
            f.write(f"{{acc}}\\n")

    print()
    print("="*70)
    print(f"Total accessions: {{len(all_accessions)}}")
    print(f"Saved to: {{output_file}}")
    print()
    print("{strategy} breakdown:")
    for year, month, count in period_counts:
        print(f"  {{year}}-{{month:02d}}: {{count}} samples")
    print("="*70)

if __name__ == "__main__":
    main()
'''

    return script_content

def generate_sbatch_script(config):
    """Generate matching sbatch script for COMPASS pipeline"""
    organism = config['organism']
    org_filename = organism.lower().replace(' ', '_')
    start_year = config['start_year']
    end_year = config['end_year']
    strategy = config['strategy']
    samples_per_period = config['samples_per_period']

    accession_file = f"sra_accessions_{org_filename}_{strategy.lower()}_{samples_per_period}_{start_year}-{end_year}.txt"

    sbatch_content = f'''#!/bin/bash
#SBATCH --job-name=compass_{org_filename}
#SBATCH --output=/homes/tylerdoe/slurm-compass-{org_filename}-%j.out
#SBATCH --error=/homes/tylerdoe/slurm-compass-{org_filename}-%j.err
#SBATCH --time=168:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=tdoerks@vet.k-state.edu

echo "=========================================="
echo "COMPASS Pipeline - {organism}"
echo "Sampling: {samples_per_period} per {strategy.lower()}"
echo "Period: {start_year} - {end_year}"
echo "=========================================="
echo "Job ID: $SLURM_JOB_ID"
echo "Start time: $(date)"
echo ""

# Change to fastscratch directory
cd /fastscratch/tylerdoe/COMPASS-pipeline || {{
    echo "ERROR: Could not cd to /fastscratch/tylerdoe/COMPASS-pipeline"
    exit 1
}}

# Load Nextflow
module load Nextflow || {{
    echo "ERROR: Could not load Nextflow"
    exit 1
}}

# Set unique Nextflow home to avoid cache conflicts
export NXF_HOME=/fastscratch/tylerdoe/.nextflow_{org_filename}

# Set output directory
OUTPUT_DIR="/fastscratch/tylerdoe/{org_filename}_{start_year}_{end_year}_$(date +%Y%m%d)"

echo "Working directory: $(pwd)"
echo "Input file: {accession_file}"
echo "Output directory: $OUTPUT_DIR"
echo ""

# Run COMPASS pipeline
nextflow run main.nf \\
    -profile beocat \\
    --input_mode sra_list \\
    --input {accession_file} \\
    --skip_busco false \\
    --busco_download_path /fastscratch/tylerdoe/databases/busco_downloads \\
    --prophage_db /fastscratch/tylerdoe/databases/prophage_db.dmnd \\
    --outdir "$OUTPUT_DIR" \\
    -w work_{org_filename} \\
    -resume

EXIT_CODE=$?

echo ""
echo "=========================================="
echo "End time: $(date)"
echo "Exit code: $EXIT_CODE"
echo "=========================================="

if [ $EXIT_CODE -eq 0 ]; then
    echo "✅ Pipeline completed successfully!"
    echo "Results: $OUTPUT_DIR"
else
    echo "❌ Pipeline failed with exit code $EXIT_CODE"
    echo "Check logs: /homes/tylerdoe/slurm-compass-{org_filename}-${{SLURM_JOB_ID}}.out"
fi

exit $EXIT_CODE
'''

    return sbatch_content

def main():
    print("="*70)
    print("  COMPASS Pipeline - Interactive Accession List Generator")
    print("="*70)
    print()
    print("This tool will generate a custom Python script to fetch SRA accessions")
    print("from NCBI based on your sampling requirements.")
    print()

    config = {}

    # Get organism
    print("1. What organism do you want to study?")
    print("   Examples: Escherichia coli, Salmonella, Klebsiella pneumoniae")
    config['organism'] = get_input("Organism", "Escherichia coli")

    # Get time period
    print("\n2. What time period?")
    current_year = datetime.now().year
    config['start_year'] = get_int("Start year", 2020, min_val=2000, max_val=current_year)
    config['end_year'] = get_int("End year", current_year, min_val=config['start_year'], max_val=current_year)

    # Get sampling strategy
    print("\n3. What sampling strategy?")
    print("   1) Monthly (X samples per month)")
    print("   2) Yearly (X samples per year)")
    print("   3) All available")
    strategy_choice = get_input("Choice", "1", choices=['1', '2', '3'])

    if strategy_choice == '1':
        config['strategy'] = 'Monthly'
        config['samples_per_period'] = get_int("Samples per month", 100, min_val=1)
    elif strategy_choice == '2':
        config['strategy'] = 'Yearly'
        config['samples_per_period'] = get_int("Samples per year", 1000, min_val=1)
    else:
        config['strategy'] = 'All'
        config['samples_per_period'] = 999999  # Effectively unlimited

    # Get platform
    print("\n4. What sequencing platform?")
    print("   Options: Illumina, PacBio, Nanopore, Any")
    config['platform'] = get_input("Platform", "Illumina")

    # Get library source
    print("\n5. What library source?")
    print("   Options: GENOMIC, METAGENOMIC, TRANSCRIPTOMIC, Any")
    config['library_source'] = get_input("Library source", "GENOMIC")

    # Get optional geographic filter
    print("\n6. Geographic location filter (optional)")
    print("   Examples: KS, USA, China, or leave blank for all")
    geo = input("Geographic filter [none]: ").strip()
    if geo:
        config['geo_filter'] = geo

    # Generate files
    print("\n" + "="*70)
    print("Generating files...")
    print("="*70)

    # Generate Python script
    org_filename = config['organism'].lower().replace(' ', '_')
    python_filename = f"fetch_{org_filename}_{config['strategy'].lower()}_{config['samples_per_period']}_{config['start_year']}-{config['end_year']}.py"

    with open(python_filename, 'w') as f:
        f.write(generate_script(config))
    os.chmod(python_filename, 0o755)

    # Generate sbatch script
    sbatch_filename = f"run_{org_filename}_{config['strategy'].lower()}_{config['start_year']}-{config['end_year']}.sh"

    with open(sbatch_filename, 'w') as f:
        f.write(generate_sbatch_script(config))
    os.chmod(sbatch_filename, 0o755)

    # Calculate estimates
    years = config['end_year'] - config['start_year'] + 1
    if config['strategy'] == 'Monthly':
        estimated_samples = years * 12 * config['samples_per_period']
        periods = years * 12
    elif config['strategy'] == 'Yearly':
        estimated_samples = years * config['samples_per_period']
        periods = years
    else:
        estimated_samples = "Unknown"
        periods = years * 12

    # Print summary
    print()
    print("✓ Generated files:")
    print(f"  1. {python_filename}")
    print(f"  2. {sbatch_filename}")
    print()
    print("Summary:")
    print(f"  Organism: {config['organism']}")
    print(f"  Period: {config['start_year']} - {config['end_year']}")
    print(f"  Strategy: {config['strategy']}")
    print(f"  Samples per period: {config['samples_per_period']}")
    print(f"  Estimated total: ~{estimated_samples} samples" if estimated_samples != "Unknown" else "  Estimated total: All available")
    print(f"  Runtime: ~{periods} minutes (1 sec per API call)")
    print()
    print("Next steps:")
    print(f"  1. python3 {python_filename}")
    print(f"  2. sbatch {sbatch_filename}")
    print()
    print("="*70)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nCancelled by user")
        sys.exit(1)
